language: python
python:
  - "2.7"
  - "2.6"

env:
  global:
    - SHINKEN_DEST=$HOME/tmp_shinken

install:
  - ./test/setup_module_test.sh

script:
  - export PYTHONPATH=$SHINKEN_DEST:$PYTHONPATH
  - nosetests -xv --with-coverage --cover-package=booster_nrpe test

after_success:
  coveralls

notifications:
  email: false
